
name: docker-metamart-ingestion-base-slim docker

on:
  workflow_dispatch:
    inputs:
      docker_release_tag:
        description: "Ingestion Base Slim Docker Image Tag (3 digit docker image tag)"
        required: true
      pypi_release_version:
        description: "Provide the Release Version (4 digit docker image tag)"
        required: true
      push_latest_tag_to_release:
        description: "Do you want to update docker image latest tag as well ?"
        type: boolean

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the Repo
        uses: actions/checkout@v4

      - name: Prepare for Docker Build&Push
        id: prepare
        uses: ./.github/actions/prepare-for-docker-build-and-push
        with:
          image: metamart/ingestion-base-slim
          tag: ${{ inputs.docker_release_tag }}
          push_latest: ${{ inputs.push_latest_tag_to_release }}
          is_ingestion: true
          release_version: ${{ inputs.pypi_release_version }}
          dockerhub_username: ${{ secrets.DOCKERHUB_METAMART_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_METAMART_TOKEN }}

      - name: Build and push if event is workflow_dispatch and input is checked
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_NO_SUMMARY: true
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prepare.outputs.tags }}
          file: ./ingestion/operators/docker/Dockerfile
          build-args: |
            INGESTION_DEPENDENCY=slim
