
name: Publish Package to Maven Central Repository

on:
  workflow_dispatch:
          
#  push:
#    branches:
#      - main
#    paths:
#      - "metamart-service/**"
#      - "metamart-spec/src/main/resources/json/schema/**"
#      - "metamart-clients/**"
#      - "pom.xml"
#      - ".github/workflows/publish-maven-package.yml"

permissions:
  contents: read

jobs:
  publish-maven-packages:
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
            tool-cache: false
            android: true
            dotnet: true
            haskell: true
            large-packages: false
            swap-storage: true
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev python3-venv librdkafka-dev gcc libsasl2-dev build-essential libssl-dev libffi-dev \
          librdkafka-dev unixodbc-dev libevent-dev
      - name: Setup Test Containers Properties
        run: |
          sudo make install_antlr_cli
          echo 'testcontainers.reuse.enable=true' >> $HOME/.testcontainers.properties
      - name: Setup settings-security.xml
        run: |
          rm -rf ~/.m2/settings-security.xml
          echo "<settingsSecurity><master>${{ secrets.MAVEN_MASTER_PASSWORD }}</master></settingsSecurity>" > ~/.m2/settings-security.xml
      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Publish to Central Repository
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
            -DskipTests -Prelease clean deploy
