
# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Selenium No Ingestion Java CI

on:
#  push:
#    branches:
#      - main
#      - '0.[0-9]+.[0-9]+'
#    paths:
#      - 'metamart-ui/src/main/resources/ui/**'
#      - 'metamart-ui/src/test/java/org/metamart/catalog/selenium/pagesWithoutData/**'
  pull_request:
    branches:
      - main
      - '0.[0-9]+.[0-9]+'
    paths:
      - 'metamart-ui/src/main/resources/ui/**'
      - 'metamart-ui/src/test/java/org/metamart/catalog/selenium/pagesWithoutData/**'

permissions:
  contents: read

concurrency: 
  group: selenium-noIngestion-tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true      
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generating Data Models
      run: |
        sudo make install_antlr_cli
        make install_dev generate

    - name: Maven Package
      run: mvn -DskipTests clean package

    - name: Start Server
      run: cd ./docker/development && docker-compose up -d metamart-server mysql elasticsearch
      timeout-minutes: 20

    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash

    - name: Run Page Tests without data
      run: mvn clean test -Dtest="org.metamart.catalog.selenium.pagesWithoutData.**.*.java" -DfailIfNoTests=false

